[project]
authors = ["ethanc8 <echaroenpitaks@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "simple-rail-sim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
